services:
  app:
    build:
      context: ./docker_app
      dockerfile: Dockerfile
    ports:
      - 3000:3306
    volumes:
      - ./:/docker_app
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
      - $HOME/.aws/config:/root/.aws/config:ro
    environment:
      MYSQL_HOST: mysql #database-1.c5huywdwn3ev.us-east-1.rds.amazonaws.com
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_DB: nfl
    depends_on:
      - mysql

  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etcmysql
    environment:
      - MYSQL_ROOT_PASSWORD=example

#  postgres:
#    image: postgres:14.1-alpine
#    restart: always
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    ports:
#      - '5432:5432'
#    volumes:
#      - db:/var/lib/postgresql/data

#  mongo:
#    image: mongo
#    container_name: mongodb
#    ports:
#      - 27017:27017
#    volumes:
#      - nfl-mongo-data:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example

#  grafana:
#    image: grafana/grafana:7.5.7
#    ports:
#      - 3000:3000
#    restart: unless-stopped
#    volumes:
#      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
#      - grafana-data:/var/lib/grafana


volumes:
  mysql_data:
  mysql_config:
#  nfl-mongo-data:
#  grafana-data: