from os import environ as env
import boto3
from botocore.exceptions import ClientError
from ast import literal_eval

def get_secret():

    secret_name = "rds!db-5acbe245-84bb-4fc7-948e-2102db463eef"
    region_name = "us-east-1"

    # Create a Secrets Manager client
    session = boto3.session.Session()
    client = session.client(
        service_name='secretsmanager',
        region_name=region_name
    )

    try:
        get_secret_value_response = client.get_secret_value(
            SecretId=secret_name
        )
    except ClientError as e:
        # For a list of exceptions thrown, see
        # https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetSecretValue.html
        raise e

    # Decrypts secret using the associated KMS key - response is a string that looks like:
    #   '{"username": "foo", "password": "bar"}'
    secret_string = get_secret_value_response['SecretString']

    # turns string response into a dict and then returns just the pw
    secret = literal_eval(secret_string)['password']
    return secret



team_map = {
    "Arizona Cardinals": "ARI",
    "Atlanta Falcons": "ATL",
    "Baltimore Ravens": "BAL",
    "Buffalo Bills": "BUF",
    "Carolina Panthers": "",
    "Chicago Bears": "CHI",
    "Cincinnati Bengals": "CIN",
    "Cleveland Browns": "CLE",
    "Dallas Cowboys": "DAL",
    "Denver Broncos": "DEN",
    "Detroit Lions": "DET",
    "Green Bay Packers": "GNB",
    "Houston Texans": "HOU",
    "Indianapolis Colts": "IND",
    "Jacksonville Jaguars": "JAX",
    "Kansas City Chiefs": "KAN",
    "Las Vegas Raiders": "LVR",
    "Los Angeles Chargers": "LAC",
    "Los Angeles Rams": "LAR",
    "Miami Dolphins": "MIA",
    "Minnesota Vikings": "MIN",
    "New England Patriots": "NWE",
    "New Orleans Saints": "NOR",
    "New York Giants": "NYG",
    "New York Jets": "NYJ",
    "Philadelphia Eagles": "PHI",
    "Pittsburgh Steelers": "PIT",
    "San Francisco 49ers": "SFO",
    "Seattle Seahawks": "SEA",
    "Tampa Bay Buccaneers": "TAM",
    "Tennessee Titans": "TEN",
    "Washington Commanders": "WAS"
}

s3_bucket = "s3://fantasyland-bucket-1"
s3_key = "player_input_lists/FantasyPros_2022_Ros_ALL_Rankings.csv"

sqs_queue_name = "fantasyland-queue"

# RDS
mysql_user = env.get("MYSQL_USER", "root")
mysql_pw = get_secret()
mysql_host = env.get("MYSQL_HOST", "database-1.c5huywdwn3ev.us-east-1.rds.amazonaws.com")
mysql_port = env.get("MYSQL_PORT", "3306")
mysql_db = env.get("MYSQL_DB", "nfl")

# Docker
# mysql_user = env.get("MYSQL_USER", "root")
# mysql_pw = env.get("MYSQL_PW", "example")
# mysql_host = env.get("MYSQL_HOST", "127.0.0.1")
# mysql_port = env.get("MYSQL_PORT", "3306")
# mysql_db = env.get("MYSQL_DB", "nfl")

sql_table_configs = {
    "player_info_table": ("CREATE TABLE IF NOT EXISTS `player_info_table` ("
                          "  `pid` varchar(80) NOT NULL,"
                          "  `fn` TEXT NOT NULL," 
                          "  `ln` TEXT NOT NULL,"
                          "  `pos` TEXT NOT NULL,"
                          "  `team` TEXT NOT NULL,"
                          "  `age` TEXT NOT NULL,"
                          "  PRIMARY KEY (`pid`)"
                          ") ENGINE=InnoDB"),

    "gamelog_table": ("CREATE TABLE IF NOT EXISTS `gamelog_table` ("
                      "`pid` VARCHAR(200),"
                      "`fn` TEXT NOT NULL," 
                      "`ln` TEXT NOT NULL,"
                      "`ranker` VARCHAR(200),"
                      "`game_date` VARCHAR(200),"
                      "`game_num` VARCHAR(200),"
                      "`week_num` VARCHAR(200),"
                      "`age` VARCHAR(200),"
                      "`team` VARCHAR(200),"
                      "`game_location` VARCHAR(200),"
                      "`opp` VARCHAR(200),"
                      "`game_result` VARCHAR(200),"
                      "`gs` VARCHAR(200),"
                      "`targets` VARCHAR(200),"
                      "`rec` VARCHAR(200),"
                      "`rec_yds` VARCHAR(200),"
                      "`rec_yds_per_rec` VARCHAR(200),"
                      "`rec_td` VARCHAR(200),"
                      "`catch_pct` VARCHAR(200),"
                      "`rec_yds_per_tgt` VARCHAR(200),"
                      "`rush_att` VARCHAR(200),"
                      "`rush_yds` VARCHAR(200),"
                      "`rush_yds_per_att` VARCHAR(200),"
                      "`rush_td` VARCHAR(200),"
                      "`pass_cmp` VARCHAR(200),"
                      "`pass_att` VARCHAR(200),"
                      "`pass_cmp_perc` VARCHAR(200),"
                      "`pass_yds` VARCHAR(200),"
                      "`pass_td` VARCHAR(200),"
                      "`pass_int` VARCHAR(200),"
                      "`pass_rating` VARCHAR(200),"
                      "`pass_sacked` VARCHAR(200),"
                      "`pass_sacked_yds` VARCHAR(200),"
                      "`pass_yds_per_att` VARCHAR(200),"
                      "`pass_adj_yds_per_att` VARCHAR(200),"
                      "`kick_ret` VARCHAR(200),"
                      "`kick_ret_yds` VARCHAR(200),"
                      "`kick_ret_yds_per_ret` VARCHAR(200),"
                      "`kick_ret_td` VARCHAR(200),"
                      "`punt_ret` VARCHAR(200),"
                      "`punt_ret_yds` VARCHAR(200),"
                      "`punt_ret_yds_per_ret` VARCHAR(200),"
                      "`punt_ret_td` VARCHAR(200),"
                      "`two_pt_md` VARCHAR(200),"
                      "`all_td` VARCHAR(200),"
                      "`scoring` VARCHAR(200),"
                      "`sacks` VARCHAR(200),"
                      "`tackles_solo` VARCHAR(200),"
                      "`tackles_assists` VARCHAR(200),"
                      "`tackles_combined` VARCHAR(200),"
                      "`tackles_loss` VARCHAR(200),"
                      "`qb_hits` VARCHAR(200),"
                      "`fumbles` VARCHAR(200),"
                      "`fumbles_lost` VARCHAR(200),"
                      "`fumbles_forced` VARCHAR(200),"
                      "`fumbles_rec` VARCHAR(200),"
                      "`fumbles_rec_yds` VARCHAR(200),"
                      "`fumbles_rec_td` VARCHAR(200),"
                      "`offense` VARCHAR(200),"
                      "`off_pct` VARCHAR(200),"
                      "`defense` VARCHAR(200),"
                      "`def_pct` VARCHAR(200),"
                      "`special_teams` VARCHAR(200),"
                      "`st_pct` VARCHAR(200),"
                      "`status` VARCHAR(200),"
                      "`reason` VARCHAR(200)"
                      ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"),

    "fantasy_table": ("CREATE TABLE IF NOT EXISTS `fantasy_table` ("
                      "`pid` VARCHAR(200),"
                      "`fn` TEXT NOT NULL," 
                      "`ln` TEXT NOT NULL,"
                      "`ranker` VARCHAR(200),"
                      "`game_num` VARCHAR(200),"
                      "`game_date` VARCHAR(200),"
                      "`team` VARCHAR(200),"
                      "`game_location` VARCHAR(200),"
                      "`opp` VARCHAR(200),"
                      "`game_result` VARCHAR(200),"
                      "`starter_pos` VARCHAR(200),"
                      "`pass_cmp` VARCHAR(200),"
                      "`pass_att` VARCHAR(200),"
                      "`pass_yds` VARCHAR(200),"
                      "`pass_td` VARCHAR(200),"
                      "`rush_att` VARCHAR(200),"
                      "`rush_yds` VARCHAR(200),"
                      "`rush_td` VARCHAR(200),"
                      "`targets` VARCHAR(200),"
                      "`rec` VARCHAR(200),"
                      "`rec_yds` VARCHAR(200),"
                      "`rec_td` VARCHAR(200),"
                      "`pass_cmp_in_10` VARCHAR(200),"
                      "`pass_att_in_10` VARCHAR(200),"
                      "`pass_yds_in_10` VARCHAR(200),"
                      "`pass_td_in_10` VARCHAR(200),"
                      "`rush_att_in_10` VARCHAR(200),"
                      "`rush_yds_in_10` VARCHAR(200),"
                      "`rush_td_in_10` VARCHAR(200),"
                      "`targets_in_10` VARCHAR(200),"
                      "`rec_in_10` VARCHAR(200),"
                      "`rec_yds_in_10` VARCHAR(200),"
                      "`rec_td_in_10` VARCHAR(200),"
                      "`offense` VARCHAR(200),"
                      "`off_pct` VARCHAR(200),"
                      "`defense` VARCHAR(200),"
                      "`def_pct` VARCHAR(200),"
                      "`special_teams` VARCHAR(200),"
                      "`st_pct` VARCHAR(200),"
                      "`fantasy_points` VARCHAR(200),"
                      "`draftkings_points` VARCHAR(200),"
                      "`fanduel_points` VARCHAR(200)"
                      ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"),

    "dynasty_scoring_table": ("CREATE TABLE IF NOT EXISTS `dynasty_scoring_table` ("
                              "`pid` VARCHAR(200),"
                              "`fn` TEXT NOT NULL," 
                              "`ln` TEXT NOT NULL,"
                              "`0` VARCHAR(200)"
                              ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"),

    "adv_rush_rec_table": ("CREATE TABLE IF NOT EXISTS `adv_rush_rec_table` ("
                           "`pid` VARCHAR(200),"
                           "`fn` TEXT NOT NULL," 
                           "`ln` TEXT NOT NULL,"
                           "`ranker` VARCHAR(200),"
                           "`game_date` VARCHAR(200),"
                           "`game_num` VARCHAR(200),"
                           "`week_num` VARCHAR(200),"
                           "`age` VARCHAR(200),"
                           "`team` VARCHAR(200),"
                           "`game_location` VARCHAR(200),"
                           "`opp` VARCHAR(200),"
                           "`game_result` VARCHAR(200),"
                           "`targets` VARCHAR(200),"
                           "`rec` VARCHAR(200),"
                           "`rec_yds` VARCHAR(200),"
                           "`rec_td` VARCHAR(200),"
                           "`rec_first_down` VARCHAR(200),"
                           "`rec_air_yds` VARCHAR(200),"
                           "`rec_air_yds_per_rec` VARCHAR(200),"
                           "`rec_yac` VARCHAR(200),"
                           "`rec_yac_per_rec` VARCHAR(200),"
                           "`rec_adot` VARCHAR(200),"
                           "`rec_broken_tackles` VARCHAR(200),"
                           "`rec_broken_tackles_per_rec` VARCHAR(200),"
                           "`rec_drops` VARCHAR(200),"
                           "`rec_drop_pct` VARCHAR(200),"
                           "`rec_target_int` VARCHAR(200),"
                           "`rec_pass_rating` VARCHAR(200),"
                           "`rush_att` VARCHAR(200),"
                           "`rush_yds` VARCHAR(200),"
                           "`rush_td` VARCHAR(200),"
                           "`rush_first_down` VARCHAR(200),"
                           "`rush_yds_before_contact` VARCHAR(200),"
                           "`rush_yds_bc_per_rush` VARCHAR(200),"
                           "`rush_yac` VARCHAR(200),"
                           "`rush_yac_per_rush` VARCHAR(200),"
                           "`rush_broken_tackles` VARCHAR(200),"
                           "`rush_broken_tackles_per_rush` VARCHAR(200)"
                           ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"),

    "adv_pass_table": ("CREATE TABLE IF NOT EXISTS `adv_pass_table` ("
                       "`pid` VARCHAR(200),"
                       "`fn` TEXT NOT NULL," 
                       "`ln` TEXT NOT NULL,"
                       "`ranker` VARCHAR(200),"
                       "`game_date` VARCHAR(200),"
                       "`game_num` VARCHAR(200),"
                       "`week_num` VARCHAR(200),"
                       "`age` VARCHAR(200),"
                       "`team` VARCHAR(200),"
                       "`game_location` VARCHAR(200),"
                       "`opp` VARCHAR(200),"
                       "`game_result` VARCHAR(200),"
                       "`pass_cmp` VARCHAR(200),"
                       "`pass_att` VARCHAR(200),"
                       "`pass_yds` VARCHAR(200),"
                       "`pass_first_down` VARCHAR(200),"
                       "`pass_first_down_pct` VARCHAR(200),"
                       "`pass_target_yds` VARCHAR(200),"
                       "`pass_tgt_yds_per_att` VARCHAR(200),"
                       "`pass_air_yds` VARCHAR(200),"
                       "`pass_air_yds_per_cmp` VARCHAR(200),"
                       "`pass_air_yds_per_att` VARCHAR(200),"
                       "`pass_yac` VARCHAR(200),"
                       "`pass_yac_per_cmp` VARCHAR(200),"
                       "`pass_drops` VARCHAR(200),"
                       "`pass_drop_pct` VARCHAR(200),"
                       "`pass_poor_throws` VARCHAR(200),"
                       "`pass_poor_throw_pct` VARCHAR(200),"
                       "`pass_sacked` VARCHAR(200),"
                       "`pass_blitzed` VARCHAR(200),"
                       "`pass_hurried` VARCHAR(200),"
                       "`pass_hits` VARCHAR(200),"
                       "`pass_pressured` VARCHAR(200),"
                       "`pass_pressured_pct` VARCHAR(200),"
                       "`rush_scrambles` VARCHAR(200),"
                       "`rush_scrambles_yds_per_att` VARCHAR(200)"
                       ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"),

    "splits_place_table": ("CREATE TABLE IF NOT EXISTS `splits_place_table` ("
                           "`pid` VARCHAR(200),"
                           "`fn` TEXT NOT NULL," 
                           "`ln` TEXT NOT NULL,"
                           "`g` VARCHAR(200),"
                           "`wins` VARCHAR(200),"
                           "`losses` VARCHAR(200),"
                           "`ties` VARCHAR(200),"
                           "`targets` VARCHAR(200),"
                           "`rec` VARCHAR(200),"
                           "`rec_yds` VARCHAR(200),"
                           "`rec_yds_per_rec` VARCHAR(200),"
                           "`rec_td` VARCHAR(200),"
                           "`rec_first_down` VARCHAR(200),"
                           "`catch_pct` VARCHAR(200),"
                           "`rec_yds_per_tgt` VARCHAR(200),"
                           "`rec_per_g` VARCHAR(200),"
                           "`rec_yds_per_g` VARCHAR(200),"
                           "`rush_att` VARCHAR(200),"
                           "`rush_yds` VARCHAR(200),"
                           "`rush_yds_per_att` VARCHAR(200),"
                           "`rush_td` VARCHAR(200),"
                           "`rush_first_down` VARCHAR(200),"
                           "`rush_att_per_g` VARCHAR(200),"
                           "`rush_yds_per_g` VARCHAR(200),"
                           "`pass_cmp` VARCHAR(200),"
                           "`pass_att` VARCHAR(200),"
                           "`pass_inc` VARCHAR(200),"
                           "`pass_cmp_perc` VARCHAR(200),"
                           "`pass_yds` VARCHAR(200),"
                           "`pass_td` VARCHAR(200),"
                           "`pass_first_down` VARCHAR(200),"
                           "`pass_int` VARCHAR(200),"
                           "`pass_rating` VARCHAR(200),"
                           "`pass_sacked` VARCHAR(200),"
                           "`pass_sacked_yds` VARCHAR(200),"
                           "`pass_yds_per_att` VARCHAR(200),"
                           "`pass_adj_yds_per_att` VARCHAR(200),"
                           "`pass_att_per_g` VARCHAR(200),"
                           "`pass_yds_per_g` VARCHAR(200),"
                           "`kick_ret` VARCHAR(200),"
                           "`kick_ret_yds` VARCHAR(200),"
                           "`kick_ret_yds_per_ret` VARCHAR(200),"
                           "`kick_ret_td` VARCHAR(200),"
                           "`punt_ret` VARCHAR(200),"
                           "`punt_ret_yds` VARCHAR(200),"
                           "`punt_ret_yds_per_ret` VARCHAR(200),"
                           "`punt_ret_td` VARCHAR(200),"
                           "`two_pt_md` VARCHAR(200),"
                           "`all_td` VARCHAR(200),"
                           "`scoring` VARCHAR(200),"
                           "`fumbles` VARCHAR(200),"
                           "`fumbles_lost` VARCHAR(200),"
                           "`fumbles_forced` VARCHAR(200),"
                           "`fumbles_rec` VARCHAR(200),"
                           "`fumbles_rec_yds` VARCHAR(200),"
                           "`fumbles_rec_td` VARCHAR(200)"
                           ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"),

    "splits_result_table": ("CREATE TABLE IF NOT EXISTS `splits_result_table` ("
                            "`pid` VARCHAR(200),"
                            "`fn` TEXT NOT NULL," 
                            "`ln` TEXT NOT NULL,"
                            "`g` VARCHAR(200),"
                            "`wins` VARCHAR(200),"
                            "`losses` VARCHAR(200),"
                            "`ties` VARCHAR(200),"
                            "`targets` VARCHAR(200),"
                            "`rec` VARCHAR(200),"
                            "`rec_yds` VARCHAR(200),"
                            "`rec_yds_per_rec` VARCHAR(200),"
                            "`rec_td` VARCHAR(200),"
                            "`rec_first_down` VARCHAR(200),"
                            "`catch_pct` VARCHAR(200),"
                            "`rec_yds_per_tgt` VARCHAR(200),"
                            "`rec_per_g` VARCHAR(200),"
                            "`rec_yds_per_g` VARCHAR(200),"
                            "`rush_att` VARCHAR(200),"
                            "`rush_yds` VARCHAR(200),"
                            "`rush_yds_per_att` VARCHAR(200),"
                            "`rush_td` VARCHAR(200),"
                            "`rush_first_down` VARCHAR(200),"
                            "`rush_att_per_g` VARCHAR(200),"
                            "`rush_yds_per_g` VARCHAR(200),"
                            "`pass_cmp` VARCHAR(200),"
                            "`pass_att` VARCHAR(200),"
                            "`pass_inc` VARCHAR(200),"
                            "`pass_cmp_perc` VARCHAR(200),"
                            "`pass_yds` VARCHAR(200),"
                            "`pass_td` VARCHAR(200),"
                            "`pass_first_down` VARCHAR(200),"
                            "`pass_int` VARCHAR(200),"
                            "`pass_rating` VARCHAR(200),"
                            "`pass_sacked` VARCHAR(200),"
                            "`pass_sacked_yds` VARCHAR(200),"
                            "`pass_yds_per_att` VARCHAR(200),"
                            "`pass_adj_yds_per_att` VARCHAR(200),"
                            "`pass_att_per_g` VARCHAR(200),"
                            "`pass_yds_per_g` VARCHAR(200),"
                            "`kick_ret` VARCHAR(200),"
                            "`kick_ret_yds` VARCHAR(200),"
                            "`kick_ret_yds_per_ret` VARCHAR(200),"
                            "`kick_ret_td` VARCHAR(200),"
                            "`punt_ret` VARCHAR(200),"
                            "`punt_ret_yds` VARCHAR(200),"
                            "`punt_ret_yds_per_ret` VARCHAR(200),"
                            "`punt_ret_td` VARCHAR(200),"
                            "`two_pt_md` VARCHAR(200),"
                            "`all_td` VARCHAR(200),"
                            "`scoring` VARCHAR(200),"
                            "`fumbles` VARCHAR(200),"
                            "`fumbles_lost` VARCHAR(200),"
                            "`fumbles_forced` VARCHAR(200),"
                            "`fumbles_rec` VARCHAR(200),"
                            "`fumbles_rec_yds` VARCHAR(200),"
                            "`fumbles_rec_td` VARCHAR(200)"
                            ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"),

    "splits_final_margin_table": ("CREATE TABLE IF NOT EXISTS `splits_final_margin_table` ("
                                  "`pid` VARCHAR(200),"
                                  "`fn` TEXT NOT NULL," 
                                  "`ln` TEXT NOT NULL,"
                                  "`g` VARCHAR(200),"
                                  "`wins` VARCHAR(200),"
                                  "`losses` VARCHAR(200),"
                                  "`ties` VARCHAR(200),"
                                  "`targets` VARCHAR(200),"
                                  "`rec` VARCHAR(200),"
                                  "`rec_yds` VARCHAR(200),"
                                  "`rec_yds_per_rec` VARCHAR(200),"
                                  "`rec_td` VARCHAR(200),"
                                  "`rec_first_down` VARCHAR(200),"
                                  "`catch_pct` VARCHAR(200),"
                                  "`rec_yds_per_tgt` VARCHAR(200),"
                                  "`rec_per_g` VARCHAR(200),"
                                  "`rec_yds_per_g` VARCHAR(200),"
                                  "`rush_att` VARCHAR(200),"
                                  "`rush_yds` VARCHAR(200),"
                                  "`rush_yds_per_att` VARCHAR(200),"
                                  "`rush_td` VARCHAR(200),"
                                  "`rush_first_down` VARCHAR(200),"
                                  "`rush_att_per_g` VARCHAR(200),"
                                  "`rush_yds_per_g` VARCHAR(200),"
                                  "`pass_cmp` VARCHAR(200),"
                                  "`pass_att` VARCHAR(200),"
                                  "`pass_inc` VARCHAR(200),"
                                  "`pass_cmp_perc` VARCHAR(200),"
                                  "`pass_yds` VARCHAR(200),"
                                  "`pass_td` VARCHAR(200),"
                                  "`pass_first_down` VARCHAR(200),"
                                  "`pass_int` VARCHAR(200),"
                                  "`pass_rating` VARCHAR(200),"
                                  "`pass_sacked` VARCHAR(200),"
                                  "`pass_sacked_yds` VARCHAR(200),"
                                  "`pass_yds_per_att` VARCHAR(200),"
                                  "`pass_adj_yds_per_att` VARCHAR(200),"
                                  "`pass_att_per_g` VARCHAR(200),"
                                  "`pass_yds_per_g` VARCHAR(200),"
                                  "`kick_ret` VARCHAR(200),"
                                  "`kick_ret_yds` VARCHAR(200),"
                                  "`kick_ret_yds_per_ret` VARCHAR(200),"
                                  "`kick_ret_td` VARCHAR(200),"
                                  "`punt_ret` VARCHAR(200),"
                                  "`punt_ret_yds` VARCHAR(200),"
                                  "`punt_ret_yds_per_ret` VARCHAR(200),"
                                  "`punt_ret_td` VARCHAR(200),"
                                  "`two_pt_md` VARCHAR(200),"
                                  "`all_td` VARCHAR(200),"
                                  "`scoring` VARCHAR(200),"
                                  "`fumbles` VARCHAR(200),"
                                  "`fumbles_lost` VARCHAR(200),"
                                  "`fumbles_forced` VARCHAR(200),"
                                  "`fumbles_rec` VARCHAR(200),"
                                  "`fumbles_rec_yds` VARCHAR(200),"
                                  "`fumbles_rec_td` VARCHAR(200)"
                                  ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"),

    "splits_month_table": ("CREATE TABLE IF NOT EXISTS `splits_month_table` ("
                           "`pid` VARCHAR(200),"
                           "`fn` TEXT NOT NULL," 
                           "`ln` TEXT NOT NULL,"
                           "`g` VARCHAR(200),"
                           "`wins` VARCHAR(200),"
                           "`losses` VARCHAR(200),"
                           "`ties` VARCHAR(200),"
                           "`targets` VARCHAR(200),"
                           "`rec` VARCHAR(200),"
                           "`rec_yds` VARCHAR(200),"
                           "`rec_yds_per_rec` VARCHAR(200),"
                           "`rec_td` VARCHAR(200),"
                           "`rec_first_down` VARCHAR(200),"
                           "`catch_pct` VARCHAR(200),"
                           "`rec_yds_per_tgt` VARCHAR(200),"
                           "`rec_per_g` VARCHAR(200),"
                           "`rec_yds_per_g` VARCHAR(200),"
                           "`rush_att` VARCHAR(200),"
                           "`rush_yds` VARCHAR(200),"
                           "`rush_yds_per_att` VARCHAR(200),"
                           "`rush_td` VARCHAR(200),"
                           "`rush_first_down` VARCHAR(200),"
                           "`rush_att_per_g` VARCHAR(200),"
                           "`rush_yds_per_g` VARCHAR(200),"
                           "`pass_cmp` VARCHAR(200),"
                           "`pass_att` VARCHAR(200),"
                           "`pass_inc` VARCHAR(200),"
                           "`pass_cmp_perc` VARCHAR(200),"
                           "`pass_yds` VARCHAR(200),"
                           "`pass_td` VARCHAR(200),"
                           "`pass_first_down` VARCHAR(200),"
                           "`pass_int` VARCHAR(200),"
                           "`pass_rating` VARCHAR(200),"
                           "`pass_sacked` VARCHAR(200),"
                           "`pass_sacked_yds` VARCHAR(200),"
                           "`pass_yds_per_att` VARCHAR(200),"
                           "`pass_adj_yds_per_att` VARCHAR(200),"
                           "`pass_att_per_g` VARCHAR(200),"
                           "`pass_yds_per_g` VARCHAR(200),"
                           "`kick_ret` VARCHAR(200),"
                           "`kick_ret_yds` VARCHAR(200),"
                           "`kick_ret_yds_per_ret` VARCHAR(200),"
                           "`kick_ret_td` VARCHAR(200),"
                           "`punt_ret` VARCHAR(200),"
                           "`punt_ret_yds` VARCHAR(200),"
                           "`punt_ret_yds_per_ret` VARCHAR(200),"
                           "`punt_ret_td` VARCHAR(200),"
                           "`two_pt_md` VARCHAR(200),"
                           "`all_td` VARCHAR(200),"
                           "`scoring` VARCHAR(200),"
                           "`fumbles` VARCHAR(200),"
                           "`fumbles_lost` VARCHAR(200),"
                           "`fumbles_forced` VARCHAR(200),"
                           "`fumbles_rec` VARCHAR(200),"
                           "`fumbles_rec_yds` VARCHAR(200),"
                           "`fumbles_rec_td` VARCHAR(200)"
                           ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"),

    "splits_game_number_table": ("CREATE TABLE IF NOT EXISTS `splits_game_number_table` ("
                                 "`pid` VARCHAR(200),"
                                 "`fn` TEXT NOT NULL," 
                                 "`ln` TEXT NOT NULL,"
                                 "`g` VARCHAR(200),"
                                 "`wins` VARCHAR(200),"
                                 "`losses` VARCHAR(200),"
                                 "`ties` VARCHAR(200),"
                                 "`targets` VARCHAR(200),"
                                 "`rec` VARCHAR(200),"
                                 "`rec_yds` VARCHAR(200),"
                                 "`rec_yds_per_rec` VARCHAR(200),"
                                 "`rec_td` VARCHAR(200),"
                                 "`rec_first_down` VARCHAR(200),"
                                 "`catch_pct` VARCHAR(200),"
                                 "`rec_yds_per_tgt` VARCHAR(200),"
                                 "`rec_per_g` VARCHAR(200),"
                                 "`rec_yds_per_g` VARCHAR(200),"
                                 "`rush_att` VARCHAR(200),"
                                 "`rush_yds` VARCHAR(200),"
                                 "`rush_yds_per_att` VARCHAR(200),"
                                 "`rush_td` VARCHAR(200),"
                                 "`rush_first_down` VARCHAR(200),"
                                 "`rush_att_per_g` VARCHAR(200),"
                                 "`rush_yds_per_g` VARCHAR(200),"
                                 "`pass_cmp` VARCHAR(200),"
                                 "`pass_att` VARCHAR(200),"
                                 "`pass_inc` VARCHAR(200),"
                                 "`pass_cmp_perc` VARCHAR(200),"
                                 "`pass_yds` VARCHAR(200),"
                                 "`pass_td` VARCHAR(200),"
                                 "`pass_first_down` VARCHAR(200),"
                                 "`pass_int` VARCHAR(200),"
                                 "`pass_rating` VARCHAR(200),"
                                 "`pass_sacked` VARCHAR(200),"
                                 "`pass_sacked_yds` VARCHAR(200),"
                                 "`pass_yds_per_att` VARCHAR(200),"
                                 "`pass_adj_yds_per_att` VARCHAR(200),"
                                 "`pass_att_per_g` VARCHAR(200),"
                                 "`pass_yds_per_g` VARCHAR(200),"
                                 "`kick_ret` VARCHAR(200),"
                                 "`kick_ret_yds` VARCHAR(200),"
                                 "`kick_ret_yds_per_ret` VARCHAR(200),"
                                 "`kick_ret_td` VARCHAR(200),"
                                 "`punt_ret` VARCHAR(200),"
                                 "`punt_ret_yds` VARCHAR(200),"
                                 "`punt_ret_yds_per_ret` VARCHAR(200),"
                                 "`punt_ret_td` VARCHAR(200),"
                                 "`two_pt_md` VARCHAR(200),"
                                 "`all_td` VARCHAR(200),"
                                 "`scoring` VARCHAR(200),"
                                 "`fumbles` VARCHAR(200),"
                                 "`fumbles_lost` VARCHAR(200),"
                                 "`fumbles_forced` VARCHAR(200),"
                                 "`fumbles_rec` VARCHAR(200),"
                                 "`fumbles_rec_yds` VARCHAR(200),"
                                 "`fumbles_rec_td` VARCHAR(200)"
                                 ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"),

    "splits_day_table": ("CREATE TABLE IF NOT EXISTS `splits_day_table` ("
                         "`pid` VARCHAR(200),"
                         "`fn` TEXT NOT NULL," 
                         "`ln` TEXT NOT NULL,"
                         "`g` VARCHAR(200),"
                         "`wins` VARCHAR(200),"
                         "`losses` VARCHAR(200),"
                         "`ties` VARCHAR(200),"
                         "`targets` VARCHAR(200),"
                         "`rec` VARCHAR(200),"
                         "`rec_yds` VARCHAR(200),"
                         "`rec_yds_per_rec` VARCHAR(200),"
                         "`rec_td` VARCHAR(200),"
                         "`rec_first_down` VARCHAR(200),"
                         "`catch_pct` VARCHAR(200),"
                         "`rec_yds_per_tgt` VARCHAR(200),"
                         "`rec_per_g` VARCHAR(200),"
                         "`rec_yds_per_g` VARCHAR(200),"
                         "`rush_att` VARCHAR(200),"
                         "`rush_yds` VARCHAR(200),"
                         "`rush_yds_per_att` VARCHAR(200),"
                         "`rush_td` VARCHAR(200),"
                         "`rush_first_down` VARCHAR(200),"
                         "`rush_att_per_g` VARCHAR(200),"
                         "`rush_yds_per_g` VARCHAR(200),"
                         "`pass_cmp` VARCHAR(200),"
                         "`pass_att` VARCHAR(200),"
                         "`pass_inc` VARCHAR(200),"
                         "`pass_cmp_perc` VARCHAR(200),"
                         "`pass_yds` VARCHAR(200),"
                         "`pass_td` VARCHAR(200),"
                         "`pass_first_down` VARCHAR(200),"
                         "`pass_int` VARCHAR(200),"
                         "`pass_rating` VARCHAR(200),"
                         "`pass_sacked` VARCHAR(200),"
                         "`pass_sacked_yds` VARCHAR(200),"
                         "`pass_yds_per_att` VARCHAR(200),"
                         "`pass_adj_yds_per_att` VARCHAR(200),"
                         "`pass_att_per_g` VARCHAR(200),"
                         "`pass_yds_per_g` VARCHAR(200),"
                         "`kick_ret` VARCHAR(200),"
                         "`kick_ret_yds` VARCHAR(200),"
                         "`kick_ret_yds_per_ret` VARCHAR(200),"
                         "`kick_ret_td` VARCHAR(200),"
                         "`punt_ret` VARCHAR(200),"
                         "`punt_ret_yds` VARCHAR(200),"
                         "`punt_ret_yds_per_ret` VARCHAR(200),"
                         "`punt_ret_td` VARCHAR(200),"
                         "`two_pt_md` VARCHAR(200),"
                         "`all_td` VARCHAR(200),"
                         "`scoring` VARCHAR(200),"
                         "`fumbles` VARCHAR(200),"
                         "`fumbles_lost` VARCHAR(200),"
                         "`fumbles_forced` VARCHAR(200),"
                         "`fumbles_rec` VARCHAR(200),"
                         "`fumbles_rec_yds` VARCHAR(200),"
                         "`fumbles_rec_td` VARCHAR(200)"
                         ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"),

    "splits_time_table": ("CREATE TABLE IF NOT EXISTS `splits_time_table` ("
                          "`pid` VARCHAR(200),"
                          "`fn` TEXT NOT NULL," 
                          "`ln` TEXT NOT NULL,"
                          "`g` VARCHAR(200),"
                          "`wins` VARCHAR(200),"
                          "`losses` VARCHAR(200),"
                          "`ties` VARCHAR(200),"
                          "`targets` VARCHAR(200),"
                          "`rec` VARCHAR(200),"
                          "`rec_yds` VARCHAR(200),"
                          "`rec_yds_per_rec` VARCHAR(200),"
                          "`rec_td` VARCHAR(200),"
                          "`rec_first_down` VARCHAR(200),"
                          "`catch_pct` VARCHAR(200),"
                          "`rec_yds_per_tgt` VARCHAR(200),"
                          "`rec_per_g` VARCHAR(200),"
                          "`rec_yds_per_g` VARCHAR(200),"
                          "`rush_att` VARCHAR(200),"
                          "`rush_yds` VARCHAR(200),"
                          "`rush_yds_per_att` VARCHAR(200),"
                          "`rush_td` VARCHAR(200),"
                          "`rush_first_down` VARCHAR(200),"
                          "`rush_att_per_g` VARCHAR(200),"
                          "`rush_yds_per_g` VARCHAR(200),"
                          "`pass_cmp` VARCHAR(200),"
                          "`pass_att` VARCHAR(200),"
                          "`pass_inc` VARCHAR(200),"
                          "`pass_cmp_perc` VARCHAR(200),"
                          "`pass_yds` VARCHAR(200),"
                          "`pass_td` VARCHAR(200),"
                          "`pass_first_down` VARCHAR(200),"
                          "`pass_int` VARCHAR(200),"
                          "`pass_rating` VARCHAR(200),"
                          "`pass_sacked` VARCHAR(200),"
                          "`pass_sacked_yds` VARCHAR(200),"
                          "`pass_yds_per_att` VARCHAR(200),"
                          "`pass_adj_yds_per_att` VARCHAR(200),"
                          "`pass_att_per_g` VARCHAR(200),"
                          "`pass_yds_per_g` VARCHAR(200),"
                          "`kick_ret` VARCHAR(200),"
                          "`kick_ret_yds` VARCHAR(200),"
                          "`kick_ret_yds_per_ret` VARCHAR(200),"
                          "`kick_ret_td` VARCHAR(200),"
                          "`punt_ret` VARCHAR(200),"
                          "`punt_ret_yds` VARCHAR(200),"
                          "`punt_ret_yds_per_ret` VARCHAR(200),"
                          "`punt_ret_td` VARCHAR(200),"
                          "`two_pt_md` VARCHAR(200),"
                          "`all_td` VARCHAR(200),"
                          "`scoring` VARCHAR(200),"
                          "`fumbles` VARCHAR(200),"
                          "`fumbles_lost` VARCHAR(200),"
                          "`fumbles_forced` VARCHAR(200),"
                          "`fumbles_rec` VARCHAR(200),"
                          "`fumbles_rec_yds` VARCHAR(200),"
                          "`fumbles_rec_td` VARCHAR(200)"
                          ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"),

    "splits_conference_table": ("CREATE TABLE IF NOT EXISTS `splits_conference_table` ("
                                "`pid` VARCHAR(200),"
                                "`fn` TEXT NOT NULL," 
                                "`ln` TEXT NOT NULL,"
                                "`g` VARCHAR(200),"
                                "`wins` VARCHAR(200),"
                                "`losses` VARCHAR(200),"
                                "`ties` VARCHAR(200),"
                                "`targets` VARCHAR(200),"
                                "`rec` VARCHAR(200),"
                                "`rec_yds` VARCHAR(200),"
                                "`rec_yds_per_rec` VARCHAR(200),"
                                "`rec_td` VARCHAR(200),"
                                "`rec_first_down` VARCHAR(200),"
                                "`catch_pct` VARCHAR(200),"
                                "`rec_yds_per_tgt` VARCHAR(200),"
                                "`rec_per_g` VARCHAR(200),"
                                "`rec_yds_per_g` VARCHAR(200),"
                                "`rush_att` VARCHAR(200),"
                                "`rush_yds` VARCHAR(200),"
                                "`rush_yds_per_att` VARCHAR(200),"
                                "`rush_td` VARCHAR(200),"
                                "`rush_first_down` VARCHAR(200),"
                                "`rush_att_per_g` VARCHAR(200),"
                                "`rush_yds_per_g` VARCHAR(200),"
                                "`pass_cmp` VARCHAR(200),"
                                "`pass_att` VARCHAR(200),"
                                "`pass_inc` VARCHAR(200),"
                                "`pass_cmp_perc` VARCHAR(200),"
                                "`pass_yds` VARCHAR(200),"
                                "`pass_td` VARCHAR(200),"
                                "`pass_first_down` VARCHAR(200),"
                                "`pass_int` VARCHAR(200),"
                                "`pass_rating` VARCHAR(200),"
                                "`pass_sacked` VARCHAR(200),"
                                "`pass_sacked_yds` VARCHAR(200),"
                                "`pass_yds_per_att` VARCHAR(200),"
                                "`pass_adj_yds_per_att` VARCHAR(200),"
                                "`pass_att_per_g` VARCHAR(200),"
                                "`pass_yds_per_g` VARCHAR(200),"
                                "`kick_ret` VARCHAR(200),"
                                "`kick_ret_yds` VARCHAR(200),"
                                "`kick_ret_yds_per_ret` VARCHAR(200),"
                                "`kick_ret_td` VARCHAR(200),"
                                "`punt_ret` VARCHAR(200),"
                                "`punt_ret_yds` VARCHAR(200),"
                                "`punt_ret_yds_per_ret` VARCHAR(200),"
                                "`punt_ret_td` VARCHAR(200),"
                                "`two_pt_md` VARCHAR(200),"
                                "`all_td` VARCHAR(200),"
                                "`scoring` VARCHAR(200),"
                                "`fumbles` VARCHAR(200),"
                                "`fumbles_lost` VARCHAR(200),"
                                "`fumbles_forced` VARCHAR(200),"
                                "`fumbles_rec` VARCHAR(200),"
                                "`fumbles_rec_yds` VARCHAR(200),"
                                "`fumbles_rec_td` VARCHAR(200)"
                                ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"),

    "splits_division_table": ("CREATE TABLE IF NOT EXISTS `splits_division_table` ("
                              "`pid` VARCHAR(200),"
                              "`fn` TEXT NOT NULL," 
                              "`ln` TEXT NOT NULL,"
                              "`g` VARCHAR(200),"
                              "`wins` VARCHAR(200),"
                              "`losses` VARCHAR(200),"
                              "`ties` VARCHAR(200),"
                              "`targets` VARCHAR(200),"
                              "`rec` VARCHAR(200),"
                              "`rec_yds` VARCHAR(200),"
                              "`rec_yds_per_rec` VARCHAR(200),"
                              "`rec_td` VARCHAR(200),"
                              "`rec_first_down` VARCHAR(200),"
                              "`catch_pct` VARCHAR(200),"
                              "`rec_yds_per_tgt` VARCHAR(200),"
                              "`rec_per_g` VARCHAR(200),"
                              "`rec_yds_per_g` VARCHAR(200),"
                              "`rush_att` VARCHAR(200),"
                              "`rush_yds` VARCHAR(200),"
                              "`rush_yds_per_att` VARCHAR(200),"
                              "`rush_td` VARCHAR(200),"
                              "`rush_first_down` VARCHAR(200),"
                              "`rush_att_per_g` VARCHAR(200),"
                              "`rush_yds_per_g` VARCHAR(200),"
                              "`pass_cmp` VARCHAR(200),"
                              "`pass_att` VARCHAR(200),"
                              "`pass_inc` VARCHAR(200),"
                              "`pass_cmp_perc` VARCHAR(200),"
                              "`pass_yds` VARCHAR(200),"
                              "`pass_td` VARCHAR(200),"
                              "`pass_first_down` VARCHAR(200),"
                              "`pass_int` VARCHAR(200),"
                              "`pass_rating` VARCHAR(200),"
                              "`pass_sacked` VARCHAR(200),"
                              "`pass_sacked_yds` VARCHAR(200),"
                              "`pass_yds_per_att` VARCHAR(200),"
                              "`pass_adj_yds_per_att` VARCHAR(200),"
                              "`pass_att_per_g` VARCHAR(200),"
                              "`pass_yds_per_g` VARCHAR(200),"
                              "`kick_ret` VARCHAR(200),"
                              "`kick_ret_yds` VARCHAR(200),"
                              "`kick_ret_yds_per_ret` VARCHAR(200),"
                              "`kick_ret_td` VARCHAR(200),"
                              "`punt_ret` VARCHAR(200),"
                              "`punt_ret_yds` VARCHAR(200),"
                              "`punt_ret_yds_per_ret` VARCHAR(200),"
                              "`punt_ret_td` VARCHAR(200),"
                              "`two_pt_md` VARCHAR(200),"
                              "`all_td` VARCHAR(200),"
                              "`scoring` VARCHAR(200),"
                              "`fumbles` VARCHAR(200),"
                              "`fumbles_lost` VARCHAR(200),"
                              "`fumbles_forced` VARCHAR(200),"
                              "`fumbles_rec` VARCHAR(200),"
                              "`fumbles_rec_yds` VARCHAR(200),"
                              "`fumbles_rec_td` VARCHAR(200)"
                              ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"),

    "splits_opponent_table": ("CREATE TABLE IF NOT EXISTS `splits_opponent_table` ("
                              "`pid` VARCHAR(200),"
                              "`fn` TEXT NOT NULL," 
                              "`ln` TEXT NOT NULL,"
                              "`g` VARCHAR(200),"
                              "`wins` VARCHAR(200),"
                              "`losses` VARCHAR(200),"
                              "`ties` VARCHAR(200),"
                              "`targets` VARCHAR(200),"
                              "`rec` VARCHAR(200),"
                              "`rec_yds` VARCHAR(200),"
                              "`rec_yds_per_rec` VARCHAR(200),"
                              "`rec_td` VARCHAR(200),"
                              "`rec_first_down` VARCHAR(200),"
                              "`catch_pct` VARCHAR(200),"
                              "`rec_yds_per_tgt` VARCHAR(200),"
                              "`rec_per_g` VARCHAR(200),"
                              "`rec_yds_per_g` VARCHAR(200),"
                              "`rush_att` VARCHAR(200),"
                              "`rush_yds` VARCHAR(200),"
                              "`rush_yds_per_att` VARCHAR(200),"
                              "`rush_td` VARCHAR(200),"
                              "`rush_first_down` VARCHAR(200),"
                              "`rush_att_per_g` VARCHAR(200),"
                              "`rush_yds_per_g` VARCHAR(200),"
                              "`pass_cmp` VARCHAR(200),"
                              "`pass_att` VARCHAR(200),"
                              "`pass_inc` VARCHAR(200),"
                              "`pass_cmp_perc` VARCHAR(200),"
                              "`pass_yds` VARCHAR(200),"
                              "`pass_td` VARCHAR(200),"
                              "`pass_first_down` VARCHAR(200),"
                              "`pass_int` VARCHAR(200),"
                              "`pass_rating` VARCHAR(200),"
                              "`pass_sacked` VARCHAR(200),"
                              "`pass_sacked_yds` VARCHAR(200),"
                              "`pass_yds_per_att` VARCHAR(200),"
                              "`pass_adj_yds_per_att` VARCHAR(200),"
                              "`pass_att_per_g` VARCHAR(200),"
                              "`pass_yds_per_g` VARCHAR(200),"
                              "`kick_ret` VARCHAR(200),"
                              "`kick_ret_yds` VARCHAR(200),"
                              "`kick_ret_yds_per_ret` VARCHAR(200),"
                              "`kick_ret_td` VARCHAR(200),"
                              "`punt_ret` VARCHAR(200),"
                              "`punt_ret_yds` VARCHAR(200),"
                              "`punt_ret_yds_per_ret` VARCHAR(200),"
                              "`punt_ret_td` VARCHAR(200),"
                              "`two_pt_md` VARCHAR(200),"
                              "`all_td` VARCHAR(200),"
                              "`scoring` VARCHAR(200),"
                              "`fumbles` VARCHAR(200),"
                              "`fumbles_lost` VARCHAR(200),"
                              "`fumbles_forced` VARCHAR(200),"
                              "`fumbles_rec` VARCHAR(200),"
                              "`fumbles_rec_yds` VARCHAR(200),"
                              "`fumbles_rec_td` VARCHAR(200)"
                              ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"),

    "splits_stadium_table": ("CREATE TABLE IF NOT EXISTS `splits_stadium_table` ("
                             "`pid` VARCHAR(200),"
                             "`fn` TEXT NOT NULL," 
                             "`ln` TEXT NOT NULL,"
                             "`g` VARCHAR(200),"
                             "`wins` VARCHAR(200),"
                             "`losses` VARCHAR(200),"
                             "`ties` VARCHAR(200),"
                             "`targets` VARCHAR(200),"
                             "`rec` VARCHAR(200),"
                             "`rec_yds` VARCHAR(200),"
                             "`rec_yds_per_rec` VARCHAR(200),"
                             "`rec_td` VARCHAR(200),"
                             "`rec_first_down` VARCHAR(200),"
                             "`catch_pct` VARCHAR(200),"
                             "`rec_yds_per_tgt` VARCHAR(200),"
                             "`rec_per_g` VARCHAR(200),"
                             "`rec_yds_per_g` VARCHAR(200),"
                             "`rush_att` VARCHAR(200),"
                             "`rush_yds` VARCHAR(200),"
                             "`rush_yds_per_att` VARCHAR(200),"
                             "`rush_td` VARCHAR(200),"
                             "`rush_first_down` VARCHAR(200),"
                             "`rush_att_per_g` VARCHAR(200),"
                             "`rush_yds_per_g` VARCHAR(200),"
                             "`pass_cmp` VARCHAR(200),"
                             "`pass_att` VARCHAR(200),"
                             "`pass_inc` VARCHAR(200),"
                             "`pass_cmp_perc` VARCHAR(200),"
                             "`pass_yds` VARCHAR(200),"
                             "`pass_td` VARCHAR(200),"
                             "`pass_first_down` VARCHAR(200),"
                             "`pass_int` VARCHAR(200),"
                             "`pass_rating` VARCHAR(200),"
                             "`pass_sacked` VARCHAR(200),"
                             "`pass_sacked_yds` VARCHAR(200),"
                             "`pass_yds_per_att` VARCHAR(200),"
                             "`pass_adj_yds_per_att` VARCHAR(200),"
                             "`pass_att_per_g` VARCHAR(200),"
                             "`pass_yds_per_g` VARCHAR(200),"
                             "`kick_ret` VARCHAR(200),"
                             "`kick_ret_yds` VARCHAR(200),"
                             "`kick_ret_yds_per_ret` VARCHAR(200),"
                             "`kick_ret_td` VARCHAR(200),"
                             "`punt_ret` VARCHAR(200),"
                             "`punt_ret_yds` VARCHAR(200),"
                             "`punt_ret_yds_per_ret` VARCHAR(200),"
                             "`punt_ret_td` VARCHAR(200),"
                             "`two_pt_md` VARCHAR(200),"
                             "`all_td` VARCHAR(200),"
                             "`scoring` VARCHAR(200),"
                             "`fumbles` VARCHAR(200),"
                             "`fumbles_lost` VARCHAR(200),"
                             "`fumbles_forced` VARCHAR(200),"
                             "`fumbles_rec` VARCHAR(200),"
                             "`fumbles_rec_yds` VARCHAR(200),"
                             "`fumbles_rec_td` VARCHAR(200)"
                             ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"),

    "splits_down_table": ("CREATE TABLE IF NOT EXISTS `splits_down_table` ("
                          "`pid` VARCHAR(200),"
                          "`fn` TEXT NOT NULL," 
                          "`ln` TEXT NOT NULL,"
                          "`g` VARCHAR(200),"
                          "`wins` VARCHAR(200),"
                          "`losses` VARCHAR(200),"
                          "`ties` VARCHAR(200),"
                          "`targets` VARCHAR(200),"
                          "`rec` VARCHAR(200),"
                          "`rec_yds` VARCHAR(200),"
                          "`rec_yds_per_rec` VARCHAR(200),"
                          "`rec_td` VARCHAR(200),"
                          "`rec_first_down` VARCHAR(200),"
                          "`catch_pct` VARCHAR(200),"
                          "`rec_yds_per_tgt` VARCHAR(200),"
                          "`rec_per_g` VARCHAR(200),"
                          "`rec_yds_per_g` VARCHAR(200),"
                          "`rush_att` VARCHAR(200),"
                          "`rush_yds` VARCHAR(200),"
                          "`rush_yds_per_att` VARCHAR(200),"
                          "`rush_td` VARCHAR(200),"
                          "`rush_first_down` VARCHAR(200),"
                          "`rush_att_per_g` VARCHAR(200),"
                          "`rush_yds_per_g` VARCHAR(200),"
                          "`pass_cmp` VARCHAR(200),"
                          "`pass_att` VARCHAR(200),"
                          "`pass_inc` VARCHAR(200),"
                          "`pass_cmp_perc` VARCHAR(200),"
                          "`pass_yds` VARCHAR(200),"
                          "`pass_td` VARCHAR(200),"
                          "`pass_first_down` VARCHAR(200),"
                          "`pass_int` VARCHAR(200),"
                          "`pass_rating` VARCHAR(200),"
                          "`pass_sacked` VARCHAR(200),"
                          "`pass_sacked_yds` VARCHAR(200),"
                          "`pass_yds_per_att` VARCHAR(200),"
                          "`pass_adj_yds_per_att` VARCHAR(200),"
                          "`pass_att_per_g` VARCHAR(200),"
                          "`pass_yds_per_g` VARCHAR(200),"
                          "`kick_ret` VARCHAR(200),"
                          "`kick_ret_yds` VARCHAR(200),"
                          "`kick_ret_yds_per_ret` VARCHAR(200),"
                          "`kick_ret_td` VARCHAR(200),"
                          "`punt_ret` VARCHAR(200),"
                          "`punt_ret_yds` VARCHAR(200),"
                          "`punt_ret_yds_per_ret` VARCHAR(200),"
                          "`punt_ret_td` VARCHAR(200),"
                          "`two_pt_md` VARCHAR(200),"
                          "`all_td` VARCHAR(200),"
                          "`scoring` VARCHAR(200),"
                          "`fumbles` VARCHAR(200),"
                          "`fumbles_lost` VARCHAR(200),"
                          "`fumbles_forced` VARCHAR(200),"
                          "`fumbles_rec` VARCHAR(200),"
                          "`fumbles_rec_yds` VARCHAR(200),"
                          "`fumbles_rec_td` VARCHAR(200)"
                          ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"),

    "splits_yards_to_go_table": ("CREATE TABLE IF NOT EXISTS `splits_yards_to_go_table` ("
                                 "`pid` VARCHAR(200),"
                                 "`fn` TEXT NOT NULL," 
                                 "`ln` TEXT NOT NULL,"
                                 "`g` VARCHAR(200),"
                                 "`wins` VARCHAR(200),"
                                 "`losses` VARCHAR(200),"
                                 "`ties` VARCHAR(200),"
                                 "`targets` VARCHAR(200),"
                                 "`rec` VARCHAR(200),"
                                 "`rec_yds` VARCHAR(200),"
                                 "`rec_yds_per_rec` VARCHAR(200),"
                                 "`rec_td` VARCHAR(200),"
                                 "`rec_first_down` VARCHAR(200),"
                                 "`catch_pct` VARCHAR(200),"
                                 "`rec_yds_per_tgt` VARCHAR(200),"
                                 "`rec_per_g` VARCHAR(200),"
                                 "`rec_yds_per_g` VARCHAR(200),"
                                 "`rush_att` VARCHAR(200),"
                                 "`rush_yds` VARCHAR(200),"
                                 "`rush_yds_per_att` VARCHAR(200),"
                                 "`rush_td` VARCHAR(200),"
                                 "`rush_first_down` VARCHAR(200),"
                                 "`rush_att_per_g` VARCHAR(200),"
                                 "`rush_yds_per_g` VARCHAR(200),"
                                 "`pass_cmp` VARCHAR(200),"
                                 "`pass_att` VARCHAR(200),"
                                 "`pass_inc` VARCHAR(200),"
                                 "`pass_cmp_perc` VARCHAR(200),"
                                 "`pass_yds` VARCHAR(200),"
                                 "`pass_td` VARCHAR(200),"
                                 "`pass_first_down` VARCHAR(200),"
                                 "`pass_int` VARCHAR(200),"
                                 "`pass_rating` VARCHAR(200),"
                                 "`pass_sacked` VARCHAR(200),"
                                 "`pass_sacked_yds` VARCHAR(200),"
                                 "`pass_yds_per_att` VARCHAR(200),"
                                 "`pass_adj_yds_per_att` VARCHAR(200),"
                                 "`pass_att_per_g` VARCHAR(200),"
                                 "`pass_yds_per_g` VARCHAR(200),"
                                 "`kick_ret` VARCHAR(200),"
                                 "`kick_ret_yds` VARCHAR(200),"
                                 "`kick_ret_yds_per_ret` VARCHAR(200),"
                                 "`kick_ret_td` VARCHAR(200),"
                                 "`punt_ret` VARCHAR(200),"
                                 "`punt_ret_yds` VARCHAR(200),"
                                 "`punt_ret_yds_per_ret` VARCHAR(200),"
                                 "`punt_ret_td` VARCHAR(200),"
                                 "`two_pt_md` VARCHAR(200),"
                                 "`all_td` VARCHAR(200),"
                                 "`scoring` VARCHAR(200),"
                                 "`fumbles` VARCHAR(200),"
                                 "`fumbles_lost` VARCHAR(200),"
                                 "`fumbles_forced` VARCHAR(200),"
                                 "`fumbles_rec` VARCHAR(200),"
                                 "`fumbles_rec_yds` VARCHAR(200),"
                                 "`fumbles_rec_td` VARCHAR(200)"
                                 ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"),

    "splits_down_and_yards_to_go_table": ("CREATE TABLE IF NOT EXISTS `splits_down_and_yards_to_go_table` ("
                                          "`pid` VARCHAR(200),"
                                          "`fn` TEXT NOT NULL," 
                                          "`ln` TEXT NOT NULL,"
                                          "`g` VARCHAR(200),"
                                          "`wins` VARCHAR(200),"
                                          "`losses` VARCHAR(200),"
                                          "`ties` VARCHAR(200),"
                                          "`targets` VARCHAR(200),"
                                          "`rec` VARCHAR(200),"
                                          "`rec_yds` VARCHAR(200),"
                                          "`rec_yds_per_rec` VARCHAR(200),"
                                          "`rec_td` VARCHAR(200),"
                                          "`rec_first_down` VARCHAR(200),"
                                          "`catch_pct` VARCHAR(200),"
                                          "`rec_yds_per_tgt` VARCHAR(200),"
                                          "`rec_per_g` VARCHAR(200),"
                                          "`rec_yds_per_g` VARCHAR(200),"
                                          "`rush_att` VARCHAR(200),"
                                          "`rush_yds` VARCHAR(200),"
                                          "`rush_yds_per_att` VARCHAR(200),"
                                          "`rush_td` VARCHAR(200),"
                                          "`rush_first_down` VARCHAR(200),"
                                          "`rush_att_per_g` VARCHAR(200),"
                                          "`rush_yds_per_g` VARCHAR(200),"
                                          "`pass_cmp` VARCHAR(200),"
                                          "`pass_att` VARCHAR(200),"
                                          "`pass_inc` VARCHAR(200),"
                                          "`pass_cmp_perc` VARCHAR(200),"
                                          "`pass_yds` VARCHAR(200),"
                                          "`pass_td` VARCHAR(200),"
                                          "`pass_first_down` VARCHAR(200),"
                                          "`pass_int` VARCHAR(200),"
                                          "`pass_rating` VARCHAR(200),"
                                          "`pass_sacked` VARCHAR(200),"
                                          "`pass_sacked_yds` VARCHAR(200),"
                                          "`pass_yds_per_att` VARCHAR(200),"
                                          "`pass_adj_yds_per_att` VARCHAR(200),"
                                          "`pass_att_per_g` VARCHAR(200),"
                                          "`pass_yds_per_g` VARCHAR(200),"
                                          "`kick_ret` VARCHAR(200),"
                                          "`kick_ret_yds` VARCHAR(200),"
                                          "`kick_ret_yds_per_ret` VARCHAR(200),"
                                          "`kick_ret_td` VARCHAR(200),"
                                          "`punt_ret` VARCHAR(200),"
                                          "`punt_ret_yds` VARCHAR(200),"
                                          "`punt_ret_yds_per_ret` VARCHAR(200),"
                                          "`punt_ret_td` VARCHAR(200),"
                                          "`two_pt_md` VARCHAR(200),"
                                          "`all_td` VARCHAR(200),"
                                          "`scoring` VARCHAR(200),"
                                          "`fumbles` VARCHAR(200),"
                                          "`fumbles_lost` VARCHAR(200),"
                                          "`fumbles_forced` VARCHAR(200),"
                                          "`fumbles_rec` VARCHAR(200),"
                                          "`fumbles_rec_yds` VARCHAR(200),"
                                          "`fumbles_rec_td` VARCHAR(200)"
                                          ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"),

    "splits_field_position_table": ("CREATE TABLE IF NOT EXISTS `splits_field_position_table` ("
                                    "`pid` VARCHAR(200),"
                                    "`fn` TEXT NOT NULL," 
                                    "`ln` TEXT NOT NULL,"
                                    "`g` VARCHAR(200),"
                                    "`wins` VARCHAR(200),"
                                    "`losses` VARCHAR(200),"
                                    "`ties` VARCHAR(200),"
                                    "`targets` VARCHAR(200),"
                                    "`rec` VARCHAR(200),"
                                    "`rec_yds` VARCHAR(200),"
                                    "`rec_yds_per_rec` VARCHAR(200),"
                                    "`rec_td` VARCHAR(200),"
                                    "`rec_first_down` VARCHAR(200),"
                                    "`catch_pct` VARCHAR(200),"
                                    "`rec_yds_per_tgt` VARCHAR(200),"
                                    "`rec_per_g` VARCHAR(200),"
                                    "`rec_yds_per_g` VARCHAR(200),"
                                    "`rush_att` VARCHAR(200),"
                                    "`rush_yds` VARCHAR(200),"
                                    "`rush_yds_per_att` VARCHAR(200),"
                                    "`rush_td` VARCHAR(200),"
                                    "`rush_first_down` VARCHAR(200),"
                                    "`rush_att_per_g` VARCHAR(200),"
                                    "`rush_yds_per_g` VARCHAR(200),"
                                    "`pass_cmp` VARCHAR(200),"
                                    "`pass_att` VARCHAR(200),"
                                    "`pass_inc` VARCHAR(200),"
                                    "`pass_cmp_perc` VARCHAR(200),"
                                    "`pass_yds` VARCHAR(200),"
                                    "`pass_td` VARCHAR(200),"
                                    "`pass_first_down` VARCHAR(200),"
                                    "`pass_int` VARCHAR(200),"
                                    "`pass_rating` VARCHAR(200),"
                                    "`pass_sacked` VARCHAR(200),"
                                    "`pass_sacked_yds` VARCHAR(200),"
                                    "`pass_yds_per_att` VARCHAR(200),"
                                    "`pass_adj_yds_per_att` VARCHAR(200),"
                                    "`pass_att_per_g` VARCHAR(200),"
                                    "`pass_yds_per_g` VARCHAR(200),"
                                    "`kick_ret` VARCHAR(200),"
                                    "`kick_ret_yds` VARCHAR(200),"
                                    "`kick_ret_yds_per_ret` VARCHAR(200),"
                                    "`kick_ret_td` VARCHAR(200),"
                                    "`punt_ret` VARCHAR(200),"
                                    "`punt_ret_yds` VARCHAR(200),"
                                    "`punt_ret_yds_per_ret` VARCHAR(200),"
                                    "`punt_ret_td` VARCHAR(200),"
                                    "`two_pt_md` VARCHAR(200),"
                                    "`all_td` VARCHAR(200),"
                                    "`scoring` VARCHAR(200),"
                                    "`fumbles` VARCHAR(200),"
                                    "`fumbles_lost` VARCHAR(200),"
                                    "`fumbles_forced` VARCHAR(200),"
                                    "`fumbles_rec` VARCHAR(200),"
                                    "`fumbles_rec_yds` VARCHAR(200),"
                                    "`fumbles_rec_td` VARCHAR(200)"
                                    ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"),

    "splits_score_differential_table": ("CREATE TABLE IF NOT EXISTS `splits_score_differential_table` ("
                                        "`pid` VARCHAR(200),"
                                        "`fn` TEXT NOT NULL," 
                                        "`ln` TEXT NOT NULL,"
                                        "`g` VARCHAR(200),"
                                        "`wins` VARCHAR(200),"
                                        "`losses` VARCHAR(200),"
                                        "`ties` VARCHAR(200),"
                                        "`targets` VARCHAR(200),"
                                        "`rec` VARCHAR(200),"
                                        "`rec_yds` VARCHAR(200),"
                                        "`rec_yds_per_rec` VARCHAR(200),"
                                        "`rec_td` VARCHAR(200),"
                                        "`rec_first_down` VARCHAR(200),"
                                        "`catch_pct` VARCHAR(200),"
                                        "`rec_yds_per_tgt` VARCHAR(200),"
                                        "`rec_per_g` VARCHAR(200),"
                                        "`rec_yds_per_g` VARCHAR(200),"
                                        "`rush_att` VARCHAR(200),"
                                        "`rush_yds` VARCHAR(200),"
                                        "`rush_yds_per_att` VARCHAR(200),"
                                        "`rush_td` VARCHAR(200),"
                                        "`rush_first_down` VARCHAR(200),"
                                        "`rush_att_per_g` VARCHAR(200),"
                                        "`rush_yds_per_g` VARCHAR(200),"
                                        "`pass_cmp` VARCHAR(200),"
                                        "`pass_att` VARCHAR(200),"
                                        "`pass_inc` VARCHAR(200),"
                                        "`pass_cmp_perc` VARCHAR(200),"
                                        "`pass_yds` VARCHAR(200),"
                                        "`pass_td` VARCHAR(200),"
                                        "`pass_first_down` VARCHAR(200),"
                                        "`pass_int` VARCHAR(200),"
                                        "`pass_rating` VARCHAR(200),"
                                        "`pass_sacked` VARCHAR(200),"
                                        "`pass_sacked_yds` VARCHAR(200),"
                                        "`pass_yds_per_att` VARCHAR(200),"
                                        "`pass_adj_yds_per_att` VARCHAR(200),"
                                        "`pass_att_per_g` VARCHAR(200),"
                                        "`pass_yds_per_g` VARCHAR(200),"
                                        "`kick_ret` VARCHAR(200),"
                                        "`kick_ret_yds` VARCHAR(200),"
                                        "`kick_ret_yds_per_ret` VARCHAR(200),"
                                        "`kick_ret_td` VARCHAR(200),"
                                        "`punt_ret` VARCHAR(200),"
                                        "`punt_ret_yds` VARCHAR(200),"
                                        "`punt_ret_yds_per_ret` VARCHAR(200),"
                                        "`punt_ret_td` VARCHAR(200),"
                                        "`two_pt_md` VARCHAR(200),"
                                        "`all_td` VARCHAR(200),"
                                        "`scoring` VARCHAR(200),"
                                        "`fumbles` VARCHAR(200),"
                                        "`fumbles_lost` VARCHAR(200),"
                                        "`fumbles_forced` VARCHAR(200),"
                                        "`fumbles_rec` VARCHAR(200),"
                                        "`fumbles_rec_yds` VARCHAR(200),"
                                        "`fumbles_rec_td` VARCHAR(200)"
                                        ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"),

    "splits_quarter_table": ("CREATE TABLE IF NOT EXISTS `splits_quarter_table` ("
                             "`pid` VARCHAR(200),"
                             "`fn` TEXT NOT NULL," 
                             "`ln` TEXT NOT NULL,"
                             "`g` VARCHAR(200),"
                             "`wins` VARCHAR(200),"
                             "`losses` VARCHAR(200),"
                             "`ties` VARCHAR(200),"
                             "`targets` VARCHAR(200),"
                             "`rec` VARCHAR(200),"
                             "`rec_yds` VARCHAR(200),"
                             "`rec_yds_per_rec` VARCHAR(200),"
                             "`rec_td` VARCHAR(200),"
                             "`rec_first_down` VARCHAR(200),"
                             "`catch_pct` VARCHAR(200),"
                             "`rec_yds_per_tgt` VARCHAR(200),"
                             "`rec_per_g` VARCHAR(200),"
                             "`rec_yds_per_g` VARCHAR(200),"
                             "`rush_att` VARCHAR(200),"
                             "`rush_yds` VARCHAR(200),"
                             "`rush_yds_per_att` VARCHAR(200),"
                             "`rush_td` VARCHAR(200),"
                             "`rush_first_down` VARCHAR(200),"
                             "`rush_att_per_g` VARCHAR(200),"
                             "`rush_yds_per_g` VARCHAR(200),"
                             "`pass_cmp` VARCHAR(200),"
                             "`pass_att` VARCHAR(200),"
                             "`pass_inc` VARCHAR(200),"
                             "`pass_cmp_perc` VARCHAR(200),"
                             "`pass_yds` VARCHAR(200),"
                             "`pass_td` VARCHAR(200),"
                             "`pass_first_down` VARCHAR(200),"
                             "`pass_int` VARCHAR(200),"
                             "`pass_rating` VARCHAR(200),"
                             "`pass_sacked` VARCHAR(200),"
                             "`pass_sacked_yds` VARCHAR(200),"
                             "`pass_yds_per_att` VARCHAR(200),"
                             "`pass_adj_yds_per_att` VARCHAR(200),"
                             "`pass_att_per_g` VARCHAR(200),"
                             "`pass_yds_per_g` VARCHAR(200),"
                             "`kick_ret` VARCHAR(200),"
                             "`kick_ret_yds` VARCHAR(200),"
                             "`kick_ret_yds_per_ret` VARCHAR(200),"
                             "`kick_ret_td` VARCHAR(200),"
                             "`punt_ret` VARCHAR(200),"
                             "`punt_ret_yds` VARCHAR(200),"
                             "`punt_ret_yds_per_ret` VARCHAR(200),"
                             "`punt_ret_td` VARCHAR(200),"
                             "`two_pt_md` VARCHAR(200),"
                             "`all_td` VARCHAR(200),"
                             "`scoring` VARCHAR(200),"
                             "`fumbles` VARCHAR(200),"
                             "`fumbles_lost` VARCHAR(200),"
                             "`fumbles_forced` VARCHAR(200),"
                             "`fumbles_rec` VARCHAR(200),"
                             "`fumbles_rec_yds` VARCHAR(200),"
                             "`fumbles_rec_td` VARCHAR(200)"
                             ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"),

    "splits_game_situation_table": ("CREATE TABLE IF NOT EXISTS `splits_game_situation_table` ("
                                    "`pid` VARCHAR(200),"
                                    "`fn` TEXT NOT NULL," 
                                    "`ln` TEXT NOT NULL,"
                                    "`g` VARCHAR(200),"
                                    "`wins` VARCHAR(200),"
                                    "`losses` VARCHAR(200),"
                                    "`ties` VARCHAR(200),"
                                    "`targets` VARCHAR(200),"
                                    "`rec` VARCHAR(200),"
                                    "`rec_yds` VARCHAR(200),"
                                    "`rec_yds_per_rec` VARCHAR(200),"
                                    "`rec_td` VARCHAR(200),"
                                    "`rec_first_down` VARCHAR(200),"
                                    "`catch_pct` VARCHAR(200),"
                                    "`rec_yds_per_tgt` VARCHAR(200),"
                                    "`rec_per_g` VARCHAR(200),"
                                    "`rec_yds_per_g` VARCHAR(200),"
                                    "`rush_att` VARCHAR(200),"
                                    "`rush_yds` VARCHAR(200),"
                                    "`rush_yds_per_att` VARCHAR(200),"
                                    "`rush_td` VARCHAR(200),"
                                    "`rush_first_down` VARCHAR(200),"
                                    "`rush_att_per_g` VARCHAR(200),"
                                    "`rush_yds_per_g` VARCHAR(200),"
                                    "`pass_cmp` VARCHAR(200),"
                                    "`pass_att` VARCHAR(200),"
                                    "`pass_inc` VARCHAR(200),"
                                    "`pass_cmp_perc` VARCHAR(200),"
                                    "`pass_yds` VARCHAR(200),"
                                    "`pass_td` VARCHAR(200),"
                                    "`pass_first_down` VARCHAR(200),"
                                    "`pass_int` VARCHAR(200),"
                                    "`pass_rating` VARCHAR(200),"
                                    "`pass_sacked` VARCHAR(200),"
                                    "`pass_sacked_yds` VARCHAR(200),"
                                    "`pass_yds_per_att` VARCHAR(200),"
                                    "`pass_adj_yds_per_att` VARCHAR(200),"
                                    "`pass_att_per_g` VARCHAR(200),"
                                    "`pass_yds_per_g` VARCHAR(200),"
                                    "`kick_ret` VARCHAR(200),"
                                    "`kick_ret_yds` VARCHAR(200),"
                                    "`kick_ret_yds_per_ret` VARCHAR(200),"
                                    "`kick_ret_td` VARCHAR(200),"
                                    "`punt_ret` VARCHAR(200),"
                                    "`punt_ret_yds` VARCHAR(200),"
                                    "`punt_ret_yds_per_ret` VARCHAR(200),"
                                    "`punt_ret_td` VARCHAR(200),"
                                    "`two_pt_md` VARCHAR(200),"
                                    "`all_td` VARCHAR(200),"
                                    "`scoring` VARCHAR(200),"
                                    "`fumbles` VARCHAR(200),"
                                    "`fumbles_lost` VARCHAR(200),"
                                    "`fumbles_forced` VARCHAR(200),"
                                    "`fumbles_rec` VARCHAR(200),"
                                    "`fumbles_rec_yds` VARCHAR(200),"
                                    "`fumbles_rec_td` VARCHAR(200)"
                                    ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"),

    "splits_snap_type_and_huddle_table": ("CREATE TABLE IF NOT EXISTS `splits_snap_type_and_huddle_table` ("
                                          "`pid` VARCHAR(200),"
                                          "`fn` TEXT NOT NULL," 
                                          "`ln` TEXT NOT NULL,"
                                          "`g` VARCHAR(200),"
                                          "`wins` VARCHAR(200),"
                                          "`losses` VARCHAR(200),"
                                          "`ties` VARCHAR(200),"
                                          "`targets` VARCHAR(200),"
                                          "`rec` VARCHAR(200),"
                                          "`rec_yds` VARCHAR(200),"
                                          "`rec_yds_per_rec` VARCHAR(200),"
                                          "`rec_td` VARCHAR(200),"
                                          "`rec_first_down` VARCHAR(200),"
                                          "`catch_pct` VARCHAR(200),"
                                          "`rec_yds_per_tgt` VARCHAR(200),"
                                          "`rec_per_g` VARCHAR(200),"
                                          "`rec_yds_per_g` VARCHAR(200),"
                                          "`rush_att` VARCHAR(200),"
                                          "`rush_yds` VARCHAR(200),"
                                          "`rush_yds_per_att` VARCHAR(200),"
                                          "`rush_td` VARCHAR(200),"
                                          "`rush_first_down` VARCHAR(200),"
                                          "`rush_att_per_g` VARCHAR(200),"
                                          "`rush_yds_per_g` VARCHAR(200),"
                                          "`pass_cmp` VARCHAR(200),"
                                          "`pass_att` VARCHAR(200),"
                                          "`pass_inc` VARCHAR(200),"
                                          "`pass_cmp_perc` VARCHAR(200),"
                                          "`pass_yds` VARCHAR(200),"
                                          "`pass_td` VARCHAR(200),"
                                          "`pass_first_down` VARCHAR(200),"
                                          "`pass_int` VARCHAR(200),"
                                          "`pass_rating` VARCHAR(200),"
                                          "`pass_sacked` VARCHAR(200),"
                                          "`pass_sacked_yds` VARCHAR(200),"
                                          "`pass_yds_per_att` VARCHAR(200),"
                                          "`pass_adj_yds_per_att` VARCHAR(200),"
                                          "`pass_att_per_g` VARCHAR(200),"
                                          "`pass_yds_per_g` VARCHAR(200),"
                                          "`kick_ret` VARCHAR(200),"
                                          "`kick_ret_yds` VARCHAR(200),"
                                          "`kick_ret_yds_per_ret` VARCHAR(200),"
                                          "`kick_ret_td` VARCHAR(200),"
                                          "`punt_ret` VARCHAR(200),"
                                          "`punt_ret_yds` VARCHAR(200),"
                                          "`punt_ret_yds_per_ret` VARCHAR(200),"
                                          "`punt_ret_td` VARCHAR(200),"
                                          "`two_pt_md` VARCHAR(200),"
                                          "`all_td` VARCHAR(200),"
                                          "`scoring` VARCHAR(200),"
                                          "`fumbles` VARCHAR(200),"
                                          "`fumbles_lost` VARCHAR(200),"
                                          "`fumbles_forced` VARCHAR(200),"
                                          "`fumbles_rec` VARCHAR(200),"
                                          "`fumbles_rec_yds` VARCHAR(200),"
                                          "`fumbles_rec_td` VARCHAR(200)"
                                          ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"),

    "splits_play_action_table": ("CREATE TABLE IF NOT EXISTS `splits_play_action_table` ("
                                 "`pid` VARCHAR(200),"
                                 "`fn` TEXT NOT NULL," 
                                 "`ln` TEXT NOT NULL,"
                                 "`g` VARCHAR(200),"
                                 "`wins` VARCHAR(200),"
                                 "`losses` VARCHAR(200),"
                                 "`ties` VARCHAR(200),"
                                 "`targets` VARCHAR(200),"
                                 "`rec` VARCHAR(200),"
                                 "`rec_yds` VARCHAR(200),"
                                 "`rec_yds_per_rec` VARCHAR(200),"
                                 "`rec_td` VARCHAR(200),"
                                 "`rec_first_down` VARCHAR(200),"
                                 "`catch_pct` VARCHAR(200),"
                                 "`rec_yds_per_tgt` VARCHAR(200),"
                                 "`rec_per_g` VARCHAR(200),"
                                 "`rec_yds_per_g` VARCHAR(200),"
                                 "`rush_att` VARCHAR(200),"
                                 "`rush_yds` VARCHAR(200),"
                                 "`rush_yds_per_att` VARCHAR(200),"
                                 "`rush_td` VARCHAR(200),"
                                 "`rush_first_down` VARCHAR(200),"
                                 "`rush_att_per_g` VARCHAR(200),"
                                 "`rush_yds_per_g` VARCHAR(200),"
                                 "`pass_cmp` VARCHAR(200),"
                                 "`pass_att` VARCHAR(200),"
                                 "`pass_inc` VARCHAR(200),"
                                 "`pass_cmp_perc` VARCHAR(200),"
                                 "`pass_yds` VARCHAR(200),"
                                 "`pass_td` VARCHAR(200),"
                                 "`pass_first_down` VARCHAR(200),"
                                 "`pass_int` VARCHAR(200),"
                                 "`pass_rating` VARCHAR(200),"
                                 "`pass_sacked` VARCHAR(200),"
                                 "`pass_sacked_yds` VARCHAR(200),"
                                 "`pass_yds_per_att` VARCHAR(200),"
                                 "`pass_adj_yds_per_att` VARCHAR(200),"
                                 "`pass_att_per_g` VARCHAR(200),"
                                 "`pass_yds_per_g` VARCHAR(200),"
                                 "`kick_ret` VARCHAR(200),"
                                 "`kick_ret_yds` VARCHAR(200),"
                                 "`kick_ret_yds_per_ret` VARCHAR(200),"
                                 "`kick_ret_td` VARCHAR(200),"
                                 "`punt_ret` VARCHAR(200),"
                                 "`punt_ret_yds` VARCHAR(200),"
                                 "`punt_ret_yds_per_ret` VARCHAR(200),"
                                 "`punt_ret_td` VARCHAR(200),"
                                 "`two_pt_md` VARCHAR(200),"
                                 "`all_td` VARCHAR(200),"
                                 "`scoring` VARCHAR(200),"
                                 "`fumbles` VARCHAR(200),"
                                 "`fumbles_lost` VARCHAR(200),"
                                 "`fumbles_forced` VARCHAR(200),"
                                 "`fumbles_rec` VARCHAR(200),"
                                 "`fumbles_rec_yds` VARCHAR(200),"
                                 "`fumbles_rec_td` VARCHAR(200)"
                                 ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"),

    "splits_rpo_table": ("CREATE TABLE IF NOT EXISTS `splits_rpo_table` ("
                         "`pid` VARCHAR(200),"
                         "`fn` TEXT NOT NULL," 
                         "`ln` TEXT NOT NULL,"
                         "`g` VARCHAR(200),"
                         "`wins` VARCHAR(200),"
                         "`losses` VARCHAR(200),"
                         "`ties` VARCHAR(200),"
                         "`targets` VARCHAR(200),"
                         "`rec` VARCHAR(200),"
                         "`rec_yds` VARCHAR(200),"
                         "`rec_yds_per_rec` VARCHAR(200),"
                         "`rec_td` VARCHAR(200),"
                         "`rec_first_down` VARCHAR(200),"
                         "`catch_pct` VARCHAR(200),"
                         "`rec_yds_per_tgt` VARCHAR(200),"
                         "`rec_per_g` VARCHAR(200),"
                         "`rec_yds_per_g` VARCHAR(200),"
                         "`rush_att` VARCHAR(200),"
                         "`rush_yds` VARCHAR(200),"
                         "`rush_yds_per_att` VARCHAR(200),"
                         "`rush_td` VARCHAR(200),"
                         "`rush_first_down` VARCHAR(200),"
                         "`rush_att_per_g` VARCHAR(200),"
                         "`rush_yds_per_g` VARCHAR(200),"
                         "`pass_cmp` VARCHAR(200),"
                         "`pass_att` VARCHAR(200),"
                         "`pass_inc` VARCHAR(200),"
                         "`pass_cmp_perc` VARCHAR(200),"
                         "`pass_yds` VARCHAR(200),"
                         "`pass_td` VARCHAR(200),"
                         "`pass_first_down` VARCHAR(200),"
                         "`pass_int` VARCHAR(200),"
                         "`pass_rating` VARCHAR(200),"
                         "`pass_sacked` VARCHAR(200),"
                         "`pass_sacked_yds` VARCHAR(200),"
                         "`pass_yds_per_att` VARCHAR(200),"
                         "`pass_adj_yds_per_att` VARCHAR(200),"
                         "`pass_att_per_g` VARCHAR(200),"
                         "`pass_yds_per_g` VARCHAR(200),"
                         "`kick_ret` VARCHAR(200),"
                         "`kick_ret_yds` VARCHAR(200),"
                         "`kick_ret_yds_per_ret` VARCHAR(200),"
                         "`kick_ret_td` VARCHAR(200),"
                         "`punt_ret` VARCHAR(200),"
                         "`punt_ret_yds` VARCHAR(200),"
                         "`punt_ret_yds_per_ret` VARCHAR(200),"
                         "`punt_ret_td` VARCHAR(200),"
                         "`two_pt_md` VARCHAR(200),"
                         "`all_td` VARCHAR(200),"
                         "`scoring` VARCHAR(200),"
                         "`fumbles` VARCHAR(200),"
                         "`fumbles_lost` VARCHAR(200),"
                         "`fumbles_forced` VARCHAR(200),"
                         "`fumbles_rec` VARCHAR(200),"
                         "`fumbles_rec_yds` VARCHAR(200),"
                         "`fumbles_rec_td` VARCHAR(200)"
                         ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin")
}
